export const useCarouselBrands = () => [
  {
    imageUrl: "/brand-logo-helidream-helicopters.avif",
    alt: "brand-logo-helidream-helicopters",
    width: 300,
    height: 100,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/brand-logo-logo-roca.avif",
    alt: "brand-logo-logo-roca",
    width: 150,
    height: 150,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/brand-logo-roca-creativa.avif",
    alt: "brand-logo-roca-creativa",
    width: 200,
    height: 100,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/brand-logo-top-art-news.png",
    alt: "brand-logo-top-art-news",
    width: 200,
    height: 50,
    text: "",
    textSize: "",
  },

  {
    imageUrl: "/brand-logo-top-art-prices.png",
    alt: "brand-logo-top-art-prices",
    width: 200,
    height: 200,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/brand-logo-helidream-helicopters.avif",
    alt: "brand-logo-helidream-helicopters",
    width: 300,
    height: 100,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/brand-logo-logo-roca.avif",
    alt: "brand-logo-logo-roca",
    width: 150,
    height: 150,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/brand-logo-roca-creativa.avif",
    alt: "brand-logo-roca-creativa",
    width: 200,
    height: 100,
    text: "",
    textSize: "",
  },
  {
    imageUrl: "/brand-logo-top-art-news.png",
    alt: "brand-logo-top-art-news",
    width: 200,
    height: 50,
    text: "",
    textSize: "",
  },

  {
    imageUrl: "/brand-logo-top-art-prices.png",
    alt: "brand-logo-top-art-prices",
    width: 200,
    height: 200,
    text: "",
    textSize: "",
  },
];
